sudo: required

services:
  - docker

before_install:
  - DATE=`date +%Y.%m.%d`
  
script:
  - docker build --build-arg PBF_DATA=http://download.geofabrik.de/australia-oceania/australia-latest.osm.pbf -t jimmyww/nominatim-oceania .
  - docker tag jimmyww/nominatim-oceania jimmyww/nominatim-oceania:$DATE
  
after_success:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  - docker push jimmyww/nominatim-oceania:DATE
  - docker push jimmyww/nominatim-oceania:latest
